version: 3
workdir: .

# Architectural components (ADR-009: Layered Architecture Pattern)
#
# This configuration enforces the 4-layer architecture:
#   Entry → Command → Business Logic → Infrastructure → External Systems
#
# Key Rules:
# - Outer layers depend on inner layers, never reverse
# - Only cmd/ can import Cobra
# - internal/ packages cannot import cmd/
# - Business logic packages are isolated from each other
#
# ============================================================================
# OWNERSHIP MODEL (Framework Separation)
# ============================================================================
#
# This file has MIXED OWNERSHIP - some sections are framework-managed,
# others are project-managed. See markers below.
#
# When running `task ckeletin:update`:
# - This file is NOT automatically updated (it's in project root, not .ckeletin/)
# - Check framework CHANGELOG for any infrastructure changes
# - Manually incorporate framework improvements if needed
#
# ADDING NEW BUSINESS LOGIC:
#   When you add a new command package (e.g., internal/baseline/):
#   1. Add it to the 'business.in' list below
#   2. Run `task ckeletin:validate:layering` to verify
#
# ============================================================================

# Global allow settings
allow:
  depOnAnyVendor: true  # Allow vendor imports (external libraries)
  deepScan: false       # Disable deep AST scanning for performance
  ignoreNotFoundComponents: false  # Fail if unmatched files found

# Exclude test files, scripts, and generated files from validation
excludeFiles:
  - .*_test\.go$
  - /scripts/.*
  - /test/.*
  - /main\.go$
  - /main_test\.go$

components:
  # -------------------------------------------------------------------------
  # FRAMEWORK-MANAGED: Command Layer
  # -------------------------------------------------------------------------
  # Layer 2: Command Layer (cmd/)
  # - Ultra-thin command wrappers (ADR-001)
  # - Only layer that can import Cobra
  commands:
    in: cmd

  # -------------------------------------------------------------------------
  # FRAMEWORK-MANAGED: Infrastructure Layer
  # -------------------------------------------------------------------------
  # Layer 4: Infrastructure Layer (shared services)
  # - Configuration management (ADR-002, ADR-005) - includes subpackages
  # - Logging infrastructure (ADR-006)
  # - UI components (ADR-007)
  # - Progress reporting (with Bubble Tea support)
  # - Test utilities (testutil package)
  # - Cross-cutting concerns available to all layers
  #
  # Framework packages: .ckeletin/pkg/*
  # Project config: internal/config/commands/** (rarely changes)
  # Project UI: internal/ui/** (rarely changes)
  infrastructure:
    in:
      - .ckeletin/pkg/config/**
      - .ckeletin/pkg/logger/**
      - .ckeletin/pkg/testutil/**
      - internal/config/commands/**
      - internal/ui/**

  # -------------------------------------------------------------------------
  # PROJECT-MANAGED: Business Logic Layer
  # -------------------------------------------------------------------------
  # Layer 3: Business Logic Layer
  # - Feature-specific implementations
  # - No CLI framework dependencies
  # - Packages isolated from each other
  #
  # ⚠️  ADD YOUR BUSINESS LOGIC PACKAGES HERE
  # When adding new commands, add their internal/ packages to this list.
  # Example: Adding 'internal/baseline/**' for a new baseline command
  business:
    in:
      - internal/ping/**
      - internal/docs/**
      - internal/dev/**
      - internal/progress/**
      - internal/check/**
      # Add your business logic packages below:
      # - internal/yourpackage/**

  # -------------------------------------------------------------------------
  # PUBLIC PACKAGES: Standalone Reusable Libraries
  # -------------------------------------------------------------------------
  # pkg/ contains standalone packages that:
  # - Do NOT import from internal/ (enforced by validate-package-organization.sh)
  # - Can be imported by external Go projects
  # - Are independent of the CLI architecture
  #
  # See ADR-010 for guidance on when to use pkg/
  public:
    in:
      - pkg/**

# External dependencies (vendors from go.mod)
vendors:
  # Cobra CLI framework
  cobra:
    in: github.com/spf13/cobra

  # Viper configuration library
  viper:
    in: github.com/spf13/viper

# Common components available to all layers
commonComponents:
  - infrastructure
  - public  # Public packages can be used by any layer

# -------------------------------------------------------------------------
# FRAMEWORK-MANAGED: Dependency Rules
# -------------------------------------------------------------------------
# Dependency Rules (ADR-009)
#
# Enforces layered architecture dependency flow using allowlist approach
# - Components can ONLY depend on what's listed in mayDependOn
# - Unlisted dependencies will cause validation failures
#
# These rules rarely need modification. If you find yourself changing them,
# you may be violating the layered architecture.
deps:
  # Command layer delegates to business logic and uses infrastructure
  # Can also use Cobra and Viper (CLI framework)
  commands:
    mayDependOn:
      - business
      - infrastructure
    canUse:
      - cobra
      - viper

  # Business logic uses infrastructure only
  # Cannot import commands or other business logic
  # Cannot use Cobra (framework independence)
  business:
    mayDependOn:
      - infrastructure
    # canUse is intentionally omitted - uses only standard library + infrastructure

  # Infrastructure is the foundation
  # Cannot depend on upper layers (commands, business)
  # Can use Viper for configuration
  infrastructure:
    mayDependOn: []  # Empty - depends on nothing
    canUse:
      - viper

  # Public packages are completely standalone
  # Cannot depend on any internal packages (enforced by validation script too)
  # Can use any external vendor dependencies
  public:
    anyVendorDeps: true  # Allow external dependencies (lipgloss, etc.)
