run:
  deadline: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Check for code simplification
    - govet         # Vet examines Go source code and reports suspicious constructs
    - ineffassign   # Detects when assignments to existing variables are not used
    - staticcheck   # State of the art Go linter
    - unused        # Check for unused constants, variables, functions and types
    - gofmt         # Check if code was gofmt-ed
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go

issues:
  exclude-rules:
    - path: tools\.go
      linters: # (Optional) Apply only to specific linters
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - unused
        - gofmt
        - revive

output:
  sort-results: true

severity:
  default-severity: error
  rules:
    - linters:
        - revive
      severity: warning