# golangci-lint configuration
# See: https://golangci-lint.run/usage/configuration/
#
# Simplified configuration for golangci-lint v2
# Focuses on most impactful linters

version: 2

run:
  timeout: 5m

linters:
  enable:
    # Core linters (always enabled)
    - errcheck      # Unchecked errors
    - govet         # Suspicious constructs
    - ineffassign   # Unused assignments
    - staticcheck   # Comprehensive static analysis
    - unused        # Unused code

    # Security
    - gosec         # Security problems

    # Bugs & Correctness
    - bodyclose     # Unclosed HTTP response bodies
    - gocritic      # Comprehensive checks (performance, style, bugs)

    # Code Quality
    - misspell      # Spelling mistakes
    - revive        # General purpose linter
    - gocyclo       # Cyclomatic complexity

linters-settings:
  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G104  # Duplicates errcheck

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - gosec

    # Exclude gosec for command files (often have subprocess calls)
    - path: cmd/
      linters:
        - gosec
