# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.go"
      run: ./scripts/format-go.sh fix {staged_files}
      stage_fixed: true
    lint:
      run: task lint
    deps-verify:
      run: task deps:verify
    test:
      run: task test

pre-push:
  parallel: true
  commands:
    coverage-project:
      run: task test:coverage:project
    coverage-patch:
      run: task test:coverage:patch
