# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    format:
      glob: "*.go"
      run: task format:staged -- {staged_files}
      stage_fixed: true
    lint:
      run: task lint
    validate-constants:
      run: task validate:constants
    verify-deps:
      run: task check:deps:verify
    test:
      run: task test

pre-push:
  parallel: false
  commands:
    coverage-patch:
      run: task test:coverage:patch
    coverage-project:
      run: task test:coverage:project
