# .lefthook.yml
pre-commit:
  parallel: true
  commands:
    format:
      run: task format
    lint:
      run: task lint
    deps-verify:
      run: task deps:verify
    validate-config-patterns:
      run: task validate-config-patterns
    test:
      run: task test
