# Taskfile.yml
version: '3'

vars:
  BINARY_NAME: ckeletin-go
  MODULE_PATH: github.com/peiman/ckeletin-go
  VERSION:
    sh: git describe --tags --always --dirty
  COMMIT:
    sh: git rev-parse HEAD
  DATE:
    sh: date -u '+%Y-%m-%d_%H:%M:%S'
  LDFLAGS: >-
    -ldflags="
    -X '{{.MODULE_PATH}}/cmd.Version={{.VERSION}}'
    -X '{{.MODULE_PATH}}/cmd.Commit={{.COMMIT}}'
    -X '{{.MODULE_PATH}}/cmd.Date={{.DATE}}'
    "

tasks:
  default:
    cmds:
      - task --list
    silent: true

  setup:
    desc: Install development tools
    cmds:
    - go install golang.org/x/tools/cmd/goimports@latest
    - go install golang.org/x/vuln/cmd/govulncheck@latest
    - go install gotest.tools/gotestsum@latest
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - go install github.com/evilmartians/lefthook@latest
    - lefthook install
    silent: true

  tidy:
    desc: Ensure go.mod and go.sum are up to date
    cmds:
      - go mod tidy

  format:
    desc: Format code
    cmds:
      - goimports -w .
      - gofmt -s -w .

  lint:
    desc: Run all linters
    cmds:
      - go vet ./...
      - golangci-lint run

  vuln:
    desc: Check for vulnerabilities
    cmds:
      - govulncheck ./...

  test:
    desc: Run tests with coverage
    cmd: |
      gotestsum --format pkgname --jsonfile test-output.json --hide-summary=skipped -- -v -coverprofile=coverage.txt -covermode=atomic ./...

  test:race:
    desc: Run tests with race detection
    cmd: |
      gotestsum --format standard-verbose --jsonfile test-output.json -- -v -race ./...

  test:watch:
    desc: Run tests in watch mode
    cmd: |
      gotestsum --format pkgname --watch --hide-summary=skipped

  check:
    desc: Run all quality checks
    deps:
      - format
      - lint
      - vuln
      - test

  build:
    desc: Build the binary
    cmds:
      - go build {{.LDFLAGS}} -o {{.BINARY_NAME}} main.go

  run:
    desc: Run the application
    deps: [build]
    cmds:
      - ./{{.BINARY_NAME}}

  install:
    desc: Install the application
    cmds:
      - go install {{.LDFLAGS}} ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean
      - rm -f {{.BINARY_NAME}} coverage.txt test-output.json coverage.html
