// Code generated by scripts/generate-config-constants.go. DO NOT EDIT.

package config

// Configuration key constants - automatically generated from registry
// These constants provide compile-time safety when referencing config keys
const (
	KeyAppLogLevel          = "app.log_level"           // Logging level for the application (trace, debug, info, warn, error, fatal, pa...
	KeyAppDocsOutputFormat  = "app.docs.output_format"  // Output format for documentation (markdown, yaml)
	KeyAppDocsOutputFile    = "app.docs.output_file"    // Output file for documentation (defaults to stdout)
	KeyAppPingOutputMessage = "app.ping.output_message" // Default message to display for the ping command
	KeyAppPingOutputColor   = "app.ping.output_color"   // Text color for ping command output (white, red, green, blue, cyan, yellow, ma...
	KeyAppPingUi            = "app.ping.ui"             // Enable interactive UI for the ping command
)
